name: Core
version: '0.0.1-BETA'
main: io.github.divinerealms.core.Core
author: neonsh
description: Core plugin for FootCube Servers
depend:
  - LuckPerms
softdepend:
  - PlaceholderAPI
  - DiscordSRV
loadbefore:
  - FootCube