name: Core
version: ${version}
main: io.github.divinerealms.core.Core
author: neonsh
description: Core plugin for FootCube Servers
depend:
  - LuckPerms
  - DiscordSRV
softdepend:
  - PlaceholderAPI
  - AuthMe
  - Vault
loadbefore:
  - FootCube