name: Core
version: ${version}
main: io.github.divinerealms.core.Core
author: neonsh
description: Core plugin for FootCube Servers
depend:
  - LuckPerms
softdepend:
  - PlaceholderAPI
  - DiscordSRV
  - AuthMe
loadbefore:
  - FootCube